# Generated by Django 2.0.3 on 2018-04-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='sex',
            field=models.CharField(blank=True, choices=[(0, 'мужской'), (1, 'женский')], max_length=1,
                                   verbose_name='пол'),
        ),
    ]
