# Generated by Django 2.0.3 on 2018-04-08 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutumnSymptDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=50, verbose_name='ФИО пациента')),
                ('age', models.CharField(blank=True, choices=[('1', '< 1 года'), ('2', '1 - 5 лет'), ('3', '5 - 18 лет'), ('4', '18 - 60 лет'), ('5', '> 60 лет')], max_length=1, verbose_name='возраст')),
                ('sex', models.CharField(blank=True, choices=[('0', 'мужской'), ('1', 'женский')], max_length=1, verbose_name='пол')),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'обследование',
                'verbose_name_plural': 'обследования',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='описание')),
                ('status', models.CharField(choices=[('0', 'Диагноз подтвержден'), ('1', 'Запрос на подтверждение диагноза'), ('2', 'Диагноз отклонен')], max_length=1, verbose_name='статус диагноза')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('is_readed', models.BooleanField(default=False, verbose_name='прочитано')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=50)),
                ('organisation', models.CharField(max_length=50, verbose_name='место работы')),
                ('is_chief', models.BooleanField(default=False, verbose_name='должность главного врача')),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_type', models.CharField(choices=[('0', 'therapist'), ('1', 'neurologist'), ('2', 'ophthalmologist'), ('3', 'surgeon'), ('4', 'cardiologist')], max_length=2)),
            ],
            options={
                'verbose_name': 'специальность',
                'verbose_name_plural': 'специальности',
            },
        ),
        migrations.CreateModel(
            name='SpringSymptDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SummerSymptDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WinterSymptDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activesubstance',
            options={'verbose_name': 'aктивное вещество', 'verbose_name_plural': 'активные вещества'},
        ),
        migrations.AlterModelOptions(
            name='contraindication',
            options={'verbose_name': 'противопоказание', 'verbose_name_plural': 'противопоказания'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name': 'заболевание', 'verbose_name_plural': 'заболевания'},
        ),
        migrations.AlterModelOptions(
            name='med',
            options={'verbose_name': 'препарат', 'verbose_name_plural': 'препараты'},
        ),
        migrations.AlterModelOptions(
            name='sideeffect',
            options={'verbose_name': 'побочный эффект', 'verbose_name_plural': 'побочные эффекты'},
        ),
        migrations.AlterModelOptions(
            name='symptom',
            options={'verbose_name': 'симптом', 'verbose_name_plural': 'симптомы'},
        ),
        migrations.RemoveField(
            model_name='disease',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='disease',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='med',
            name='default_dose',
            field=models.CharField(blank=True, max_length=100, verbose_name='способ применения и дозы'),
        ),
        migrations.AddField(
            model_name='med',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='med',
            name='efficiency_class',
            field=models.IntegerField(blank=True, null=True, verbose_name='класс эффективности'),
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='activesubstance',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='meds',
            field=models.ManyToManyField(related_name='diseases', to='core.Med', verbose_name='используемые препараты'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='med',
            name='activeSubstances',
            field=models.ManyToManyField(related_name='meds', to='core.ActiveSubstance', verbose_name='активные вещества'),
        ),
        migrations.AlterField(
            model_name='med',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='класс принадлежности'),
        ),
        migrations.AlterField(
            model_name='med',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='med',
            name='side_effects',
            field=models.ManyToManyField(related_name='meds', to='core.SideEffect', verbose_name='побочные эффекты'),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='wintersymptdisease',
            name='disease',
            field=models.ManyToManyField(related_name='winter_sympt_disease', to='core.Disease'),
        ),
        migrations.AddField(
            model_name='wintersymptdisease',
            name='symptom',
            field=models.ManyToManyField(related_name='winter_sympt_disease', to='core.Symptom'),
        ),
        migrations.AddField(
            model_name='summersymptdisease',
            name='disease',
            field=models.ManyToManyField(related_name='summer_sympt_disease', to='core.Disease'),
        ),
        migrations.AddField(
            model_name='summersymptdisease',
            name='symptom',
            field=models.ManyToManyField(related_name='summer_sympt_disease', to='core.Symptom'),
        ),
        migrations.AddField(
            model_name='springsymptdisease',
            name='disease',
            field=models.ManyToManyField(related_name='spring_sympt_disease', to='core.Disease'),
        ),
        migrations.AddField(
            model_name='springsymptdisease',
            name='symptom',
            field=models.ManyToManyField(related_name='spring_sympt_disease', to='core.Symptom'),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.ManyToManyField(related_name='specializations', to='core.Specialization', verbose_name='специализации'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='notification',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disease', verbose_name='диагноз'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='examination',
            name='contraindications',
            field=models.ManyToManyField(related_name='examinations', to='core.Contraindication', verbose_name='противопоказания'),
        ),
        migrations.AddField(
            model_name='examination',
            name='diseases',
            field=models.ManyToManyField(related_name='examinations', to='core.Disease', verbose_name='заболевания'),
        ),
        migrations.AddField(
            model_name='examination',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='врач'),
        ),
        migrations.AddField(
            model_name='examination',
            name='meds',
            field=models.ManyToManyField(related_name='examinations', to='core.Med', verbose_name='лечащие препараты'),
        ),
        migrations.AddField(
            model_name='examination',
            name='symptoms',
            field=models.ManyToManyField(related_name='examinations', to='core.Symptom', verbose_name='симптомы'),
        ),
        migrations.AddField(
            model_name='autumnsymptdisease',
            name='disease',
            field=models.ManyToManyField(related_name='autumn_sympt_disease', to='core.Disease'),
        ),
        migrations.AddField(
            model_name='autumnsymptdisease',
            name='symptom',
            field=models.ManyToManyField(related_name='autumn_sympt_disease', to='core.Symptom'),
        ),
    ]
