# Generated by Django 2.0.3 on 2018-03-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutumnSymptDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SpringSymptDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SummerSymptDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WinterSymptDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='disease',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='wintersymptdisease',
            name='disease',
            field=models.ManyToManyField(related_name='winter_sympt_disease', to='core.Disease'),
        ),
        migrations.AddField(
            model_name='wintersymptdisease',
            name='symptom',
            field=models.ManyToManyField(related_name='winter_sympt_disease', to='core.Symptom'),
        ),
        migrations.AddField(
            model_name='summersymptdisease',
            name='disease',
            field=models.ManyToManyField(related_name='summer_sympt_disease', to='core.Disease'),
        ),
        migrations.AddField(
            model_name='summersymptdisease',
            name='symptom',
            field=models.ManyToManyField(related_name='summer_sympt_disease', to='core.Symptom'),
        ),
        migrations.AddField(
            model_name='springsymptdisease',
            name='disease',
            field=models.ManyToManyField(related_name='spring_sympt_disease', to='core.Disease'),
        ),
        migrations.AddField(
            model_name='springsymptdisease',
            name='symptom',
            field=models.ManyToManyField(related_name='spring_sympt_disease', to='core.Symptom'),
        ),
        migrations.AddField(
            model_name='autumnsymptdisease',
            name='disease',
            field=models.ManyToManyField(related_name='autumn_sympt_disease', to='core.Disease'),
        ),
        migrations.AddField(
            model_name='autumnsymptdisease',
            name='symptom',
            field=models.ManyToManyField(related_name='autumn_sympt_disease', to='core.Symptom'),
        ),
    ]
