# Generated by Django 2.0.3 on 2018-03-25 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20180325_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=50)),
                ('is_chief', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_type', models.CharField(choices=[('0', 'therapist')], max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activesubstance',
            options={'verbose_name': 'aктивное вещество', 'verbose_name_plural': 'активные вещества'},
        ),
        migrations.AlterModelOptions(
            name='contraindication',
            options={'verbose_name': 'противопоказание', 'verbose_name_plural': 'противопоказания'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name': 'заболевание', 'verbose_name_plural': 'заболевания'},
        ),
        migrations.AlterModelOptions(
            name='med',
            options={'verbose_name': 'препарат', 'verbose_name_plural': 'препараты'},
        ),
        migrations.AlterModelOptions(
            name='sideeffect',
            options={'verbose_name': 'побочный эффект', 'verbose_name_plural': 'побочные эффекты'},
        ),
        migrations.AlterModelOptions(
            name='symptom',
            options={'verbose_name': 'симптом', 'verbose_name_plural': 'симптомы'},
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.ManyToManyField(related_name='specializations', to='core.Specialization'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
