# Generated by Django 2.0.3 on 2018-05-15 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_auto_20180430_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(choices=[('<', '<'), ('>', '>'), ('<>', '<>')], default='<>', max_length=2,
                                          verbose_name='знак отклонения')),
            ],
        ),
        migrations.RemoveField(
            model_name='disease',
            name='analysis',
        ),
        migrations.AddField(
            model_name='analysisconstants',
            name='dimension',
            field=models.CharField(max_length=10, null=True, verbose_name='размерность'),
        ),
        migrations.AlterField(
            model_name='analysisconstants',
            name='lower_bound',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=25, verbose_name='нижняя граница'),
        ),
        migrations.AlterField(
            model_name='analysisconstants',
            name='upper_bound',
            field=models.DecimalField(decimal_places=4, max_digits=25, verbose_name='верхняя граница'),
        ),
        migrations.AlterField(
            model_name='analysisparams',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=25, verbose_name='значение'),
        ),
        migrations.AddField(
            model_name='diseaseanalysis',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AnalysisConstants',
                                    verbose_name='анализ'),
        ),
        migrations.AddField(
            model_name='diseaseanalysis',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disease',
                                    verbose_name='заболевание'),
        ),
        migrations.AddField(
            model_name='disease',
            name='analysis_constants',
            field=models.ManyToManyField(related_name='diseases', through='core.DiseaseAnalysis',
                                         to='core.AnalysisConstants', verbose_name='анализы'),
        ),
    ]
