# Generated by Django 2.0.3 on 2018-03-25 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180325_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'профиль', 'verbose_name_plural': 'профили'},
        ),
        migrations.AddField(
            model_name='autumnsymptdisease',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disease',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='med',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='med',
            name='efficiency_class',
            field=models.IntegerField(null=True, verbose_name='класс эффективности'),
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='springsymptdisease',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summersymptdisease',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wintersymptdisease',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activesubstance',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='meds',
            field=models.ManyToManyField(related_name='diseases', to='core.Med', verbose_name='используемые препараты'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='med',
            name='activeSubstances',
            field=models.ManyToManyField(related_name='meds', to='core.ActiveSubstance', verbose_name='активные вещества'),
        ),
        migrations.AlterField(
            model_name='med',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='класс принадлежности'),
        ),
        migrations.AlterField(
            model_name='med',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='med',
            name='side_effects',
            field=models.ManyToManyField(related_name='meds', to='core.SideEffect', verbose_name='побочные эффекты'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_chief',
            field=models.BooleanField(default=False, verbose_name='должность главного врача'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organisation',
            field=models.CharField(max_length=50, verbose_name='место работы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialization',
            field=models.ManyToManyField(related_name='specializations', to='core.Specialization', verbose_name='специализации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
    ]
