# Generated by Django 2.0.3 on 2018-05-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20180515_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisparams',
            name='deviation',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='отклонение'),
        ),
        migrations.AlterField(
            model_name='diseaseprobability',
            name='prob',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='вероятность'),
        ),
    ]
