# Generated by Django 2.0.3 on 2018-04-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180408_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.IntegerField(choices=[(0, 'Диагноз подтвержден'), (1, 'Запрос на подтверждение диагноза'), (2, 'Диагноз отклонен')], verbose_name='статус диагноза'),
        ),
    ]
