# Generated by Django 2.0.3 on 2018-03-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180325_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialization',
            old_name='student_type',
            new_name='spec_type',
        ),
        migrations.AlterField(
            model_name='med',
            name='efficiency_class',
            field=models.IntegerField(blank=True, null=True, verbose_name='класс эффективности'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
