# Generated by Django 2.0.3 on 2018-05-24 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_diseaseprobability_analysis_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='examination',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Disease', verbose_name='выбранный диагноз'),
        ),
        migrations.AddField(
            model_name='notification',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Examination', verbose_name='исследование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='от пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='к пользователю'),
            preserve_default=False,
        ),
    ]
