# Generated by Django 2.0.3 on 2018-03-25 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20180325_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=50, verbose_name='ФИО пациента')),
                ('age', models.CharField(blank=True, choices=[('1', '< 1 года'), ('2', '1 - 5 лет'), ('3', '5 - 18 лет'), ('4', '18 - 60 лет'), ('5', '> 60 лет')], max_length=1, verbose_name='возраст')),
                ('sex', models.CharField(blank=True, choices=[('0', 'мужской'), ('1', 'женский')], max_length=1, verbose_name='пол')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('contraindications', models.ManyToManyField(related_name='examinations', to='core.Contraindication', verbose_name='противопоказания')),
                ('diseases', models.ManyToManyField(related_name='examinations', to='core.Disease', verbose_name='заболевания')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='врач')),
            ],
            options={
                'verbose_name': 'обследование',
                'verbose_name_plural': 'обследования',
            },
        ),
        migrations.AddField(
            model_name='med',
            name='default_dose',
            field=models.CharField(blank=True, max_length=100, verbose_name='способ применения и дозы'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='spec_type',
            field=models.CharField(choices=[('0', 'therapist'), ('1', 'neurologist'), ('2', 'ophthalmologist'), ('3', 'surgeon'), ('4', 'cardiologist')], max_length=2),
        ),
        migrations.AddField(
            model_name='examination',
            name='meds',
            field=models.ManyToManyField(related_name='examinations', to='core.Med', verbose_name='лечащие препараты'),
        ),
        migrations.AddField(
            model_name='examination',
            name='symptoms',
            field=models.ManyToManyField(related_name='examinations', to=settings.AUTH_USER_MODEL, verbose_name='симптомы'),
        ),
    ]
