# Generated by Django 2.0.3 on 2018-03-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180325_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'специальность', 'verbose_name_plural': 'специальности'},
        ),
        migrations.AlterField(
            model_name='examination',
            name='symptoms',
            field=models.ManyToManyField(related_name='examinations', to='core.Symptom', verbose_name='симптомы'),
        ),
    ]
