# Generated by Django 2.0.3 on 2018-04-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_auto_20180325_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisConstants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='параметр анализа')),
                ('lower_bound', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='нижняя граница')),
                ('upper_bound', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='верхняя граница')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='параметр анализа')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='значение')),
                ('deviation', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='отклонение')),
            ],
        ),
        migrations.RemoveField(
            model_name='autumnsymptdisease',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='springsymptdisease',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='summersymptdisease',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='wintersymptdisease',
            name='counter',
        ),
        migrations.AlterField(
            model_name='specialization',
            name='spec_type',
            field=models.CharField(choices=[('0', 'терапевт'), ('1', 'невролог'), ('2', 'офтальмолог'), ('3', 'хирург'),
                                            ('4', 'кардиолог')], max_length=2),
        ),
        migrations.AddField(
            model_name='disease',
            name='analysis',
            field=models.ManyToManyField(related_name='diseases', to='core.AnalysisParams', verbose_name='анализы'),
        ),
        migrations.AddField(
            model_name='examination',
            name='analysis',
            field=models.ManyToManyField(related_name='examinations', to='core.AnalysisParams', verbose_name='анализы'),
        ),
    ]
