# Generated by Django 2.0.3 on 2018-04-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_auto_20180403_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisconstants',
            options={'verbose_name': 'критическое значения анализа',
                     'verbose_name_plural': 'критические значения анализов'},
        ),
        migrations.AlterModelOptions(
            name='analysisparams',
            options={'verbose_name': 'параметр анализа', 'verbose_name_plural': 'параметры анализа'},
        ),
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
    ]
