# Generated by Django 2.0.3 on 2018-04-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_auto_20180405_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autumnsymptdisease',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='autumnsymptdisease',
            name='symptom',
        ),
        migrations.RemoveField(
            model_name='springsymptdisease',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='springsymptdisease',
            name='symptom',
        ),
        migrations.RemoveField(
            model_name='summersymptdisease',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='summersymptdisease',
            name='symptom',
        ),
        migrations.RemoveField(
            model_name='wintersymptdisease',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='wintersymptdisease',
            name='symptom',
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(related_name='diseases', to='core.Symptom', verbose_name='симптомы'),
        ),
        migrations.DeleteModel(
            name='AutumnSymptDisease',
        ),
        migrations.DeleteModel(
            name='SpringSymptDisease',
        ),
        migrations.DeleteModel(
            name='SummerSymptDisease',
        ),
        migrations.DeleteModel(
            name='WinterSymptDisease',
        ),
    ]
