# Generated by Django 2.0.3 on 2018-04-06 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_auto_20180405_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseProbability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob', models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='вероятность')),
            ],
            options={
                'verbose_name': 'вероятность заболевания',
                'verbose_name_plural': 'вероятности заболеваний',
            },
        ),
        migrations.AddField(
            model_name='analysisconstants',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='встречаемость'),
        ),
        migrations.AddField(
            model_name='analysisparams',
            name='result',
            field=models.BooleanField(default=False, verbose_name='результат'),
        ),
        migrations.AddField(
            model_name='disease',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='встречаемость'),
        ),
        migrations.AddField(
            model_name='symptom',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='встречаемость'),
        ),
        migrations.AlterField(
            model_name='analysisparams',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_set',
                                    to='core.AnalysisConstants', verbose_name='параметр анализа'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='diseases',
            field=models.ManyToManyField(related_name='examinations', to='core.DiseaseProbability',
                                         verbose_name='заболевания'),
        ),
        migrations.AddField(
            model_name='diseaseprobability',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disease',
                                    verbose_name='заболевание'),
        ),
    ]
