# Generated by Django 2.0.3 on 2018-04-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180406_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='age',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '< 1 года'), ('2', '1 - 5 лет'), ('3', '5 - 18 лет'), ('4', '18 - 60 лет'), ('5', '> 60 лет')], max_length=1, verbose_name='возраст'),
        ),
    ]
